### ISSUE TITLE
Using template engines

### ISSUE THREAD

**Issue by jmpas** [lyef/lyef-react-cli#2]
Here is my proposal:

I think that we can create a repository for the boilerplate that this cli and the slush generator will create, both of them would use the same rep to clone it and then using a template engine to replace the stuff we want with the input data from the user (like the component name, author, etc).
https://github.com/lyef/slush-lyef-react/tree/master/component

I can make this happen if you guys agree with this idea.
What do you guys think?

**Comment by willianjusten** [comment]
![Just Do it!](https://m.popkey.co/ca8f87/AoYjv_f-maxage-0.gif)

**Comment by joao-alberto** [comment]
I think this idea is much better than manipulate files, like proposed in PR #1

**Comment by jmpas** [comment]
OMFG thank you guys for the fast feedback haha

Awesome Shia LaBeouf gif btw @willianjusten 

I'll close this issue as soon as I get this done then

**Comment by jmpas** [comment]
Hey guys
Sorry for taking so much time to start making progress with this proposal, today I was able to do some, I pushed a fat commit to master! 🎉  (sorry for the FAT commit)

I will finish it, it's not saving the processed files on disk yet 😋 

If you guys have any feedback or think that this issue can be closed don't hesitate to comment here.

**Comment by lucasbento** [comment]
Any updates on this?

I'm also willing to help, maybe you guys can create a few issues so the community can support too. 😄

**Comment by willianjusten** [comment]
I'm very busy, but @Nipher can help you, telling what he needs.

**Comment by jmpas** [comment]
Hey @lucasbento!
Awesome idea, nice to know that you are willing to help as well :)

About this issue, I think we can close it, MVP it's done...

And as @lucasbento  mentioned, we could create other issues to polish this and to create new things.

Also, we can update the slush generator to clone the [template rep](https://github.com/lyef/lyef-react-template), I'll create an issue there and then any of us can do it when available.

I want to mention that I don't have a list of things that we have to do here, I think that any of us can create issues / discuss next steps / propose changes.

But for now, I've some things in my head:
- Error handling
- Test manually the generated code and fix bugs
- Write documentation
  - Readme
  - Contributing
- Write specs for everything done until now.

Let's create issues for these items.
